-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0030_quote_execute_parity.sql:74
-- Last extracted: 2026-05-07T11:37:16.791Z
CREATE OR REPLACE FUNCTION public._speed_seconds_left_bucket(p_seconds_left double precision)
 RETURNS integer
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
  IF p_seconds_left < 10 THEN RETURN 3;
  ELSIF p_seconds_left < 30 THEN RETURN 2;
  ELSIF p_seconds_left < 60 THEN RETURN 1;
  ELSE RETURN 0;
  END IF;
END;
$function$;
COMMENT ON FUNCTION public._speed_seconds_left_bucket(p_seconds_left double precision) IS
  $$0030: classifies seconds_left into a coarse regime bucket so parity checks survive sub-second jitter but reject regime crossings.$$;
GRANT EXECUTE ON FUNCTION public._speed_seconds_left_bucket(p_seconds_left double precision) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_seconds_left_bucket(p_seconds_left double precision) TO sooqadmin;