-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0034_pricing_engine_v3.sql:177
-- Last extracted: 2026-05-12T13:54:59.688Z
CREATE OR REPLACE FUNCTION public._speed_matrix_lookup(p_asset text, p_duration speed_duration, p_dist_pct double precision, p_secs_left double precision)
 RETURNS TABLE(p_over double precision, n_eff integer, ci_width double precision, qualifies boolean, version_id integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_d_idx     SMALLINT;
  v_t_idx     SMALLINT;
  v_version   INTEGER;
BEGIN
  -- Bucketize distance
  v_d_idx := CASE
    WHEN p_dist_pct <= -0.005 THEN 0
    WHEN p_dist_pct <= -0.003 THEN 1
    WHEN p_dist_pct <= -0.002 THEN 2
    WHEN p_dist_pct <= -0.001 THEN 3
    WHEN p_dist_pct <= -0.0005 THEN 4
    WHEN p_dist_pct <  0       THEN 5
    WHEN p_dist_pct <  0.0005  THEN 6
    WHEN p_dist_pct <  0.001   THEN 7
    WHEN p_dist_pct <  0.002   THEN 8
    WHEN p_dist_pct <  0.003   THEN 9
    WHEN p_dist_pct <  0.005   THEN 10
    ELSE 11
  END;

  -- Bucketize time
  v_t_idx := CASE
    WHEN p_secs_left <= 15  THEN 0
    WHEN p_secs_left <= 30  THEN 1
    WHEN p_secs_left <= 60  THEN 2
    WHEN p_secs_left <= 120 THEN 3
    WHEN p_secs_left <= 180 THEN 4
    WHEN p_secs_left <= 240 THEN 5
    ELSE 6
  END;

  -- Get active version
  SELECT id INTO v_version
  FROM speed_pricing_matrix_versions
  WHERE asset = p_asset AND duration = p_duration AND status = 'active'
  ORDER BY computed_at DESC
  LIMIT 1;

  IF v_version IS NULL THEN
    RETURN QUERY SELECT NULL::DOUBLE PRECISION, 0, NULL::DOUBLE PRECISION, FALSE, NULL::INTEGER;
    RETURN;
  END IF;

  RETURN QUERY
    SELECT m.p_over_final, m.n_eff, m.ci_width, m.qualifies, v_version
    FROM speed_pricing_matrix m
    WHERE m.version_id = v_version
      AND m.asset = p_asset
      AND m.duration = p_duration
      AND m.dist_bucket = v_d_idx
      AND m.time_bucket = v_t_idx
    LIMIT 1;
END;
$function$;
COMMENT ON FUNCTION public._speed_matrix_lookup(p_asset text, p_duration speed_duration, p_dist_pct double precision, p_secs_left double precision) IS
  $$0034: lookup the active matrix cell for a state. Returns qualifies=false when fall back to BSM.$$;
GRANT EXECUTE ON FUNCTION public._speed_matrix_lookup(p_asset text, p_duration speed_duration, p_dist_pct double precision, p_secs_left double precision) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_matrix_lookup(p_asset text, p_duration speed_duration, p_dist_pct double precision, p_secs_left double precision) TO sooqadmin;