-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0052_phase_5a_gold_completeness/functions/_speed_is_market_open.sql
-- Last extracted: 2026-05-12T10:35:35.394Z
CREATE OR REPLACE FUNCTION public._speed_is_market_open(p_asset text, p_ts_utc timestamp with time zone DEFAULT now())
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
DECLARE
  v_hours_json jsonb;
  v_schedule   text;
  v_dow        int;     -- ISO day of week: 1=Monday, 7=Sunday
  v_hour       int;
  v_minute     int;
BEGIN
  SELECT trading_hours_json INTO v_hours_json
  FROM speed_asset_config
  WHERE asset = p_asset;

  -- No row OR no schedule → default open (24/7) — backward-compat for BTC
  IF v_hours_json IS NULL THEN
    RETURN TRUE;
  END IF;

  v_schedule := v_hours_json->>'schedule';
  IF v_schedule IS NULL OR v_schedule = 'always_open' THEN
    RETURN TRUE;
  END IF;

  IF v_schedule = 'cme_xau_aligned' THEN
    -- Compute UTC components from p_ts_utc
    v_dow    := EXTRACT(ISODOW FROM p_ts_utc AT TIME ZONE 'UTC')::int;
    v_hour   := EXTRACT(HOUR FROM p_ts_utc AT TIME ZONE 'UTC')::int;
    v_minute := EXTRACT(MINUTE FROM p_ts_utc AT TIME ZONE 'UTC')::int;

    -- Saturday (ISO 6): closed all day
    IF v_dow = 6 THEN
      RETURN FALSE;
    END IF;

    -- Sunday (ISO 7): closed until 22:00 UTC
    IF v_dow = 7 THEN
      IF v_hour < 22 THEN RETURN FALSE; END IF;
      RETURN TRUE;
    END IF;

    -- Friday (ISO 5): closed at/after 21:00 UTC
    IF v_dow = 5 THEN
      IF v_hour >= 21 THEN RETURN FALSE; END IF;
      -- Daily break still applies before 21
      IF v_hour = 21 THEN RETURN FALSE; END IF;
      RETURN TRUE;
    END IF;

    -- Monday–Thursday (ISO 1-4): closed during 21:00-22:00 UTC daily break
    IF v_hour = 21 THEN RETURN FALSE; END IF;

    RETURN TRUE;
  END IF;

  -- Unknown schedule string — fail safe and assume closed.
  RAISE WARNING '_speed_is_market_open: unknown schedule % for asset %, defaulting to closed', v_schedule, p_asset;
  RETURN FALSE;
END;
$function$;
COMMENT ON FUNCTION public._speed_is_market_open(p_asset text, p_ts_utc timestamp with time zone) IS
  $$0052 Phase 5A: returns TRUE if asset is in trading hours. Reads speed_asset_config.trading_hours_json. Backward-compat: NULL/missing JSON → always open. Used by speed_roll_markets to gate market creation, and by /api/speed/quote to show a frontend countdown when closed.$$;
GRANT EXECUTE ON FUNCTION public._speed_is_market_open(p_asset text, p_ts_utc timestamp with time zone) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_is_market_open(p_asset text, p_ts_utc timestamp with time zone) TO sooqadmin;