-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0034_pricing_engine_v3.sql:262 + commit 38922ce
-- Last extracted: 2026-05-07T10:49:59.830Z
CREATE OR REPLACE FUNCTION public._speed_pricing_apply(p_asset text, p_duration speed_duration, p_side text, p_dist_pct double precision, p_secs_left double precision, p_bsm_prob_side double precision, p_widened_spread double precision, p_mode text)
 RETURNS TABLE(mark_prob double precision, offered_prob double precision, matrix_used boolean, matrix_version integer, soft_blocked boolean)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_matrix_enabled    DECIMAL;
  v_asym_enabled      DECIMAL;
  v_soft_block_on     DECIMAL;
  v_soft_block_thresh DECIMAL;
  v_lookup            RECORD;
  v_matrix_p_over     DOUBLE PRECISION;
  v_matrix_p_side     DOUBLE PRECISION;
  v_final_mark_prob   DOUBLE PRECISION;
  v_final_offered    DOUBLE PRECISION;
  v_used_matrix       BOOLEAN := FALSE;
  v_version           INTEGER := NULL;
  v_blocked           BOOLEAN := FALSE;
  v_d_idx             SMALLINT;
  v_t_idx             SMALLINT;
  v_active_version    INTEGER;
  v_neighbor_p_over   DOUBLE PRECISION;
  v_neighbor_p_side   DOUBLE PRECISION;
BEGIN
  SELECT rate INTO v_matrix_enabled FROM fee_config WHERE fee_type = 'speed_pricing_matrix_enabled' LIMIT 1;
  SELECT rate INTO v_asym_enabled   FROM fee_config WHERE fee_type = 'speed_pricing_asym_pushup_enabled' LIMIT 1;
  v_matrix_enabled := COALESCE(v_matrix_enabled, 0);
  v_asym_enabled := COALESCE(v_asym_enabled, 1);

  -- Default to BSM
  v_final_mark_prob := p_bsm_prob_side;

  IF v_matrix_enabled = 1 THEN
    -- Resolve the active version once so neighbor queries below work even
    -- when the current cell has no row in the matrix table.
    SELECT id INTO v_active_version
    FROM speed_pricing_matrix_versions
    WHERE asset = p_asset AND duration = p_duration AND status = 'active'
    ORDER BY computed_at DESC LIMIT 1;

    -- Bucketize current state (mirrors _speed_matrix_lookup).
    -- Inlined here (not via _speed_matrix_lookup) so we have v_d_idx/v_t_idx
    -- for the neighbor query below.
    v_d_idx := CASE
      WHEN p_dist_pct <= -0.005 THEN 0
      WHEN p_dist_pct <= -0.003 THEN 1
      WHEN p_dist_pct <= -0.002 THEN 2
      WHEN p_dist_pct <= -0.001 THEN 3
      WHEN p_dist_pct <= -0.0005 THEN 4
      WHEN p_dist_pct <  0       THEN 5
      WHEN p_dist_pct <  0.0005  THEN 6
      WHEN p_dist_pct <  0.001   THEN 7
      WHEN p_dist_pct <  0.002   THEN 8
      WHEN p_dist_pct <  0.003   THEN 9
      WHEN p_dist_pct <  0.005   THEN 10
      ELSE 11
    END;
    v_t_idx := CASE
      WHEN p_secs_left <= 15  THEN 0
      WHEN p_secs_left <= 30  THEN 1
      WHEN p_secs_left <= 60  THEN 2
      WHEN p_secs_left <= 120 THEN 3
      WHEN p_secs_left <= 180 THEN 4
      WHEN p_secs_left <= 240 THEN 5
      ELSE 6
    END;

    SELECT * INTO v_lookup
    FROM _speed_matrix_lookup(p_asset, p_duration, p_dist_pct, p_secs_left)
    LIMIT 1;

    IF v_lookup.qualifies THEN
      v_used_matrix := TRUE;
      v_version := v_active_version;

      -- Matrix stores P(over wins). Convert to side-relevant.
      v_matrix_p_over := v_lookup.p_over;
      IF p_side = 'over' THEN
        v_matrix_p_side := v_matrix_p_over;
      ELSE
        v_matrix_p_side := 1.0 - v_matrix_p_over;
      END IF;

      IF v_asym_enabled = 1 THEN
        -- Asymmetric only-push-up: matrix can only RAISE the price.
        v_final_mark_prob := GREATEST(p_bsm_prob_side, v_matrix_p_side);
      ELSE
        -- Symmetric matrix (full replacement of BSM)
        v_final_mark_prob := v_matrix_p_side;
      END IF;
    ELSE
      -- 0034 [post-codex direction-matching fix]: current cell doesn't qualify,
      -- but a neighboring qualifying cell in the FAVORABLE direction may
      -- already have pushed the price up. Without this lookup, mark could
      -- regress (cell A qualified at low d with matrix=0.73, cell B at higher
      -- d falls back to BSM=0.65; favorable spot move appears to LOWER mark).
      --
      -- Neighbor logic by side:
      --   over  side: favorable = higher d. If a qualifying cell exists at
      --     LOWER d (closer to strike) with matrix p_over, that floor must
      --     propagate to current cell (P(over) is monotone non-decreasing in d).
      --   under side: favorable = lower d. Symmetric — propagate from cells
      --     at HIGHER d. (P(under) = 1 - P(over); for under to be more favorable
      --     at lower d, p_over at higher d acts as a ceiling on current p_over.)
      IF p_side = 'over' THEN
        SELECT MAX(p_over_final) INTO v_neighbor_p_over
        FROM speed_pricing_matrix
        WHERE version_id = v_active_version
          AND asset = p_asset AND duration = p_duration
          AND time_bucket = v_t_idx
          AND dist_bucket <= v_d_idx
          AND qualifies = TRUE;
        IF v_neighbor_p_over IS NOT NULL THEN
          v_neighbor_p_side := v_neighbor_p_over;
          v_used_matrix := TRUE;
          v_version := v_active_version;
          IF v_asym_enabled = 1 THEN
            v_final_mark_prob := GREATEST(p_bsm_prob_side, v_neighbor_p_side);
          ELSE
            v_final_mark_prob := v_neighbor_p_side;
          END IF;
        END IF;
      ELSE
        SELECT MIN(p_over_final) INTO v_neighbor_p_over
        FROM speed_pricing_matrix
        WHERE version_id = v_active_version
          AND asset = p_asset AND duration = p_duration
          AND time_bucket = v_t_idx
          AND dist_bucket >= v_d_idx
          AND qualifies = TRUE;
        IF v_neighbor_p_over IS NOT NULL THEN
          v_neighbor_p_side := 1.0 - v_neighbor_p_over;
          v_used_matrix := TRUE;
          v_version := v_active_version;
          IF v_asym_enabled = 1 THEN
            v_final_mark_prob := GREATEST(p_bsm_prob_side, v_neighbor_p_side);
          ELSE
            v_final_mark_prob := v_neighbor_p_side;
          END IF;
        END IF;
      END IF;
    END IF;
  END IF;

  -- Compute offered_prob (entry mode adds spread; cashout uses mark directly)
  IF p_mode = 'entry' THEN
    v_final_offered := v_final_mark_prob + p_widened_spread / 2.0;

    -- Check soft-block (entry only)
    SELECT rate INTO v_soft_block_on FROM fee_config WHERE fee_type = 'speed_entry_soft_block_enabled' LIMIT 1;
    SELECT rate INTO v_soft_block_thresh FROM fee_config WHERE fee_type = 'speed_entry_soft_block_threshold' LIMIT 1;
    v_soft_block_on := COALESCE(v_soft_block_on, 0);
    v_soft_block_thresh := COALESCE(v_soft_block_thresh, 0.95);

    IF v_soft_block_on = 1 AND v_final_offered >= v_soft_block_thresh THEN
      v_blocked := TRUE;
    END IF;
  ELSE
    -- Cashout mode: offered_prob = mark_prob (no entry spread)
    v_final_offered := v_final_mark_prob;
  END IF;

  -- Floor / cap
  IF v_final_offered < 0.01 THEN v_final_offered := 0.01; END IF;
  IF v_final_offered > 0.99 THEN v_final_offered := 0.99; END IF;
  IF v_final_mark_prob < 0.01 THEN v_final_mark_prob := 0.01; END IF;
  IF v_final_mark_prob > 0.99 THEN v_final_mark_prob := 0.99; END IF;

  RETURN QUERY SELECT v_final_mark_prob, v_final_offered, v_used_matrix, v_version, v_blocked;
END;
$function$;
COMMENT ON FUNCTION public._speed_pricing_apply(p_asset text, p_duration speed_duration, p_side text, p_dist_pct double precision, p_secs_left double precision, p_bsm_prob_side double precision, p_widened_spread double precision, p_mode text) IS
  $$0034: shared pricing helper for entry and cashout RPCs. Implements matrix lookup + asymmetric only-push-up rule + soft-block check. Single source of truth — codex hard rule.$$;
GRANT EXECUTE ON FUNCTION public._speed_pricing_apply(p_asset text, p_duration speed_duration, p_side text, p_dist_pct double precision, p_secs_left double precision, p_bsm_prob_side double precision, p_widened_spread double precision, p_mode text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_pricing_apply(p_asset text, p_duration speed_duration, p_side text, p_dist_pct double precision, p_secs_left double precision, p_bsm_prob_side double precision, p_widened_spread double precision, p_mode text) TO sooqadmin;