-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0028_pricing_engine_v2.sql:256
-- Last extracted: 2026-05-07T11:59:49.156Z
CREATE OR REPLACE FUNCTION public._speed_get_stake_max(p_duration speed_duration)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_per_dur  DECIMAL;
  v_default  DECIMAL;
BEGIN
  SELECT rate INTO v_per_dur
  FROM fee_config
  WHERE fee_type = 'speed_stake_max_' || p_duration::TEXT || '_usd';

  IF v_per_dur IS NOT NULL THEN
    RETURN v_per_dur;
  END IF;

  SELECT rate INTO v_default
  FROM fee_config
  WHERE fee_type = 'speed_stake_max_usd';

  RETURN COALESCE(v_default, 25);
END;
$function$;
COMMENT ON FUNCTION public._speed_get_stake_max(p_duration speed_duration) IS
  $$0028: per-duration per-trade max lookup with fallback to speed_stake_max_usd.$$;
GRANT EXECUTE ON FUNCTION public._speed_get_stake_max(p_duration speed_duration) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_get_stake_max(p_duration speed_duration) TO sooqadmin;