-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0052_phase_5a_gold_completeness/functions/_speed_is_market_open.sql
-- Last extracted: 2026-05-11T18:30:38.535Z
CREATE OR REPLACE FUNCTION public._speed_next_open_at(p_asset text, p_ts_utc timestamp with time zone DEFAULT now())
 RETURNS timestamp with time zone
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
DECLARE
  v_hours_json jsonb;
  v_schedule   text;
  v_dow        int;
  v_hour       int;
  v_date       date;
  v_candidate  timestamptz;
BEGIN
  -- If already open, return NULL
  IF _speed_is_market_open(p_asset, p_ts_utc) THEN
    RETURN NULL;
  END IF;

  SELECT trading_hours_json INTO v_hours_json
  FROM speed_asset_config WHERE asset = p_asset;

  v_schedule := COALESCE(v_hours_json->>'schedule', 'always_open');
  IF v_schedule = 'always_open' OR v_schedule IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_schedule = 'cme_xau_aligned' THEN
    v_dow  := EXTRACT(ISODOW FROM p_ts_utc AT TIME ZONE 'UTC')::int;
    v_hour := EXTRACT(HOUR FROM p_ts_utc AT TIME ZONE 'UTC')::int;
    v_date := (p_ts_utc AT TIME ZONE 'UTC')::date;

    -- Saturday → next open is Sunday 22:00 UTC
    IF v_dow = 6 THEN
      RETURN ((v_date + 1)::text || ' 22:00:00')::timestamptz;
    END IF;

    -- Sunday before 22:00 → today 22:00 UTC
    IF v_dow = 7 AND v_hour < 22 THEN
      RETURN (v_date::text || ' 22:00:00')::timestamptz;
    END IF;

    -- Friday at/after 21:00 → next open Sunday 22:00 UTC
    IF v_dow = 5 AND v_hour >= 21 THEN
      -- Add 2 days (Fri → Sun); date + integer = date (not timestamp)
      RETURN ((v_date + 2)::text || ' 22:00:00')::timestamptz;
    END IF;

    -- Mon-Thu daily break (21:00-22:00) → today 22:00 UTC
    IF v_hour = 21 THEN
      RETURN (v_date::text || ' 22:00:00')::timestamptz;
    END IF;

    -- Fallback (shouldn't reach here if is_market_open returned FALSE correctly)
    RETURN NULL;
  END IF;

  RETURN NULL;
END;
$function$;
COMMENT ON FUNCTION public._speed_next_open_at(p_asset text, p_ts_utc timestamp with time zone) IS
  $$0052 Phase 5A: returns next open timestamp for the asset, or NULL if currently open or schedule is always_open. Used by /api/speed/quote to power the frontend MarketClosedCountdown component.$$;
GRANT EXECUTE ON FUNCTION public._speed_next_open_at(p_asset text, p_ts_utc timestamp with time zone) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_next_open_at(p_asset text, p_ts_utc timestamp with time zone) TO sooqadmin;