-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0028_pricing_engine_v2.sql:303
-- Last extracted: 2026-05-07T11:59:46.366Z
CREATE OR REPLACE FUNCTION public._speed_cashout_margin(p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision)
 RETURNS double precision
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_dur                TEXT;
  v_base               DECIMAL;
  v_saturation_coef    DECIMAL;
  v_desperation_coef   DECIMAL;
  v_late_coef          DECIMAL;
  v_saturation         DOUBLE PRECISION;
  v_desperation        DOUBLE PRECISION;
  v_late_premium       DOUBLE PRECISION;
  v_margin             DOUBLE PRECISION;
BEGIN
  IF p_duration::TEXT NOT IN ('5m','1h') THEN
    RAISE EXCEPTION 'Cashout margin not configured for duration %', p_duration;
  END IF;
  v_dur := p_duration::TEXT;

  IF p_is_winning THEN
    -- Winning side: base + saturation premium + late-window premium.
    SELECT rate INTO v_base
    FROM fee_config
    WHERE fee_type = 'speed_cashout_winning_base_' || v_dur;
    v_base := COALESCE(v_base, CASE v_dur WHEN '5m' THEN 0.025 ELSE 0.030 END);

    SELECT rate INTO v_saturation_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_saturation_coef';
    v_saturation_coef := COALESCE(v_saturation_coef, 0.20);

    SELECT rate INTO v_late_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_late_window_winning_coef';
    v_late_coef := COALESCE(v_late_coef, 0.015);

    -- saturation = max(0, |mark − 0.5| − 0.35) × coef
    v_saturation := GREATEST(0.0, ABS(p_mark_prob::DOUBLE PRECISION - 0.5) - 0.35)
                    * v_saturation_coef::DOUBLE PRECISION;

    -- late_window = max(0, 60 − seconds_left)/60 × coef
    v_late_premium := GREATEST(0.0, (60.0 - p_seconds_left) / 60.0)
                      * v_late_coef::DOUBLE PRECISION;

    v_margin := v_base::DOUBLE PRECISION + v_saturation + v_late_premium;
  ELSE
    -- Losing side: base + desperation premium + late-window premium.
    SELECT rate INTO v_base
    FROM fee_config
    WHERE fee_type = 'speed_cashout_losing_base_' || v_dur;
    v_base := COALESCE(v_base, CASE v_dur WHEN '5m' THEN 0.080 ELSE 0.090 END);

    SELECT rate INTO v_desperation_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_desperation_coef';
    v_desperation_coef := COALESCE(v_desperation_coef, 0.40);

    SELECT rate INTO v_late_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_late_window_losing_coef';
    v_late_coef := COALESCE(v_late_coef, 0.05);

    -- desperation = max(0, 0.50 − mark) × coef
    v_desperation := GREATEST(0.0, 0.50 - p_mark_prob::DOUBLE PRECISION)
                     * v_desperation_coef::DOUBLE PRECISION;

    v_late_premium := GREATEST(0.0, (60.0 - p_seconds_left) / 60.0)
                      * v_late_coef::DOUBLE PRECISION;

    v_margin := v_base::DOUBLE PRECISION + v_desperation + v_late_premium;
  END IF;

  -- Sanity ceiling: 50% margin on either side. Should never hit at sane
  -- coefficient values; defensive cap so a misconfigured fee_config row
  -- can't push margin into 100%+ range.
  IF v_margin > 0.50 THEN
    v_margin := 0.50;
  END IF;
  IF v_margin < 0 THEN
    v_margin := 0;
  END IF;

  RETURN v_margin;
END;
$function$;
COMMENT ON FUNCTION public._speed_cashout_margin(p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision) IS
  $$0028: profit-based cashout margin (option C). Direction-matching invariant is enforced by the FORMULA shape in speed_execute_cashout, not here. This just produces the magnitude.$$;
GRANT EXECUTE ON FUNCTION public._speed_cashout_margin(p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_cashout_margin(p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision) TO sooqadmin;