-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0029_iv_cache_and_helper.sql:129
-- Last extracted: 2026-05-07T10:50:00.946Z
CREATE OR REPLACE FUNCTION public._speed_get_iv(p_asset text, p_duration speed_duration)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_horizon         TEXT;
  v_cache_row       RECORD;
  v_cache_age_secs  DOUBLE PRECISION;
  v_freshness_secs  DECIMAL;
  v_fail_closed     DECIMAL;
  v_fallback        DECIMAL;
BEGIN
  -- Map duration to cache horizon. 5m and 1h map directly. Future
  -- durations (e.g., 15m if reactivated) need to be added here.
  v_horizon := p_duration::TEXT;
  IF v_horizon NOT IN ('5m','1h','15m','24h') THEN
    RAISE EXCEPTION 'No volatility horizon mapping for duration %', p_duration;
  END IF;

  SELECT * INTO v_cache_row
  FROM speed_volatility_cache
  WHERE asset = p_asset AND horizon = v_horizon;

  -- Read fail-closed flag once.
  SELECT rate INTO v_fail_closed
  FROM fee_config WHERE fee_type = 'speed_iv_fail_closed';
  v_fail_closed := COALESCE(v_fail_closed, 0);

  IF v_cache_row IS NOT NULL THEN
    v_cache_age_secs := EXTRACT(EPOCH FROM (NOW() - v_cache_row.computed_at));

    SELECT rate INTO v_freshness_secs
    FROM fee_config
    WHERE fee_type = 'speed_iv_freshness_' || v_horizon || '_secs';
    v_freshness_secs := COALESCE(v_freshness_secs, 60);

    IF v_cache_age_secs <= v_freshness_secs THEN
      -- Fresh cache hit — primary path.
      RETURN v_cache_row.sigma_annualized;
    END IF;

    -- Stale cache.
    IF v_fail_closed > 0 THEN
      RAISE EXCEPTION 'IV cache stale for % %: % seconds old (max %s)',
        p_asset, v_horizon, ROUND(v_cache_age_secs::NUMERIC, 1), v_freshness_secs
        USING HINT = 'Oracle worker may be down. Check /api/health/oracle.';
    END IF;
    -- Fall through to fallback below.
  ELSIF v_fail_closed > 0 THEN
    RAISE EXCEPTION 'IV cache empty for % % and fail-closed mode is on',
      p_asset, v_horizon
      USING HINT = 'Oracle worker has not yet populated cache. Check services/speed-oracle/.';
  END IF;

  -- Fallback path. Used when cache is empty/stale AND fail-closed is OFF.
  -- This is the same behavior as pre-0029. After mig 0029 ships and the
  -- oracle worker is updated, the cache populates and this fallback only
  -- fires on misconfiguration or oracle outage.
  SELECT rate INTO v_fallback
  FROM fee_config WHERE fee_type = 'speed_iv_btc';

  IF v_fallback IS NULL THEN
    RAISE EXCEPTION 'IV fallback unavailable: speed_iv_btc not in fee_config';
  END IF;

  RETURN v_fallback;
END;
$function$;
COMMENT ON FUNCTION public._speed_get_iv(p_asset text, p_duration speed_duration) IS
  $$0029: returns annualized realized volatility from speed_volatility_cache. Fail-closed mode controlled by fee_config.speed_iv_fail_closed (0=fallback to speed_iv_btc, 1=raise on stale/empty).$$;
GRANT EXECUTE ON FUNCTION public._speed_get_iv(p_asset text, p_duration speed_duration) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_get_iv(p_asset text, p_duration speed_duration) TO sooqadmin;