-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0028_pricing_engine_v2.sql:303
-- Last extracted: 2026-05-11T18:57:39.965Z
CREATE OR REPLACE FUNCTION public._speed_cashout_margin(p_asset text, p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision)
 RETURNS double precision
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_mc                 speed_market_config%ROWTYPE;
  v_dur                TEXT;
  v_base               DECIMAL;
  v_saturation_coef    DECIMAL;
  v_desperation_coef   DECIMAL;
  v_late_coef          DECIMAL;
  v_saturation         DOUBLE PRECISION;
  v_desperation        DOUBLE PRECISION;
  v_late_premium       DOUBLE PRECISION;
  v_margin             DOUBLE PRECISION;
BEGIN
  IF p_duration::TEXT NOT IN ('5m','1h','1m') THEN
    RAISE EXCEPTION 'Cashout margin not configured for duration %', p_duration;
  END IF;
  v_dur := p_duration::TEXT;

  -- 0051 Phase 2C: load per-(asset, duration) row once. Empty row tolerated;
  -- COALESCE chains read fee_config fallback then hardcoded default.
  SELECT * INTO v_mc FROM speed_market_config
  WHERE asset = p_asset AND duration = p_duration;

  IF p_is_winning THEN
    -- Winning side: base + saturation premium + late-window premium.
    SELECT rate INTO v_base
    FROM fee_config
    WHERE fee_type = 'speed_cashout_winning_base_' || v_dur;
    v_base := COALESCE(
      v_mc.cashout_winning_base,
      v_base,
      CASE v_dur WHEN '5m' THEN 0.025 WHEN '1m' THEN 0.025 ELSE 0.030 END
    );

    SELECT rate INTO v_saturation_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_saturation_coef';
    v_saturation_coef := COALESCE(v_mc.cashout_saturation_coef, v_saturation_coef, 0.20);

    SELECT rate INTO v_late_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_late_window_winning_coef';
    v_late_coef := COALESCE(v_mc.cashout_late_winning_coef, v_late_coef, 0.015);

    v_saturation := GREATEST(0.0, ABS(p_mark_prob::DOUBLE PRECISION - 0.5) - 0.35)
                    * v_saturation_coef::DOUBLE PRECISION;
    v_late_premium := GREATEST(0.0, (60.0 - p_seconds_left) / 60.0)
                      * v_late_coef::DOUBLE PRECISION;
    v_margin := v_base::DOUBLE PRECISION + v_saturation + v_late_premium;
  ELSE
    -- Losing side: base + desperation premium + late-window premium.
    SELECT rate INTO v_base
    FROM fee_config
    WHERE fee_type = 'speed_cashout_losing_base_' || v_dur;
    v_base := COALESCE(
      v_mc.cashout_losing_base,
      v_base,
      CASE v_dur WHEN '5m' THEN 0.080 WHEN '1m' THEN 0.080 ELSE 0.090 END
    );

    SELECT rate INTO v_desperation_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_desperation_coef';
    v_desperation_coef := COALESCE(v_mc.cashout_desperation_coef, v_desperation_coef, 0.40);

    SELECT rate INTO v_late_coef
    FROM fee_config
    WHERE fee_type = 'speed_cashout_late_window_losing_coef';
    v_late_coef := COALESCE(v_mc.cashout_late_losing_coef, v_late_coef, 0.05);

    v_desperation := GREATEST(0.0, 0.50 - p_mark_prob::DOUBLE PRECISION)
                     * v_desperation_coef::DOUBLE PRECISION;
    v_late_premium := GREATEST(0.0, (60.0 - p_seconds_left) / 60.0)
                      * v_late_coef::DOUBLE PRECISION;
    v_margin := v_base::DOUBLE PRECISION + v_desperation + v_late_premium;
  END IF;

  IF v_margin > 0.50 THEN
    v_margin := 0.50;
  END IF;
  IF v_margin < 0 THEN
    v_margin := 0;
  END IF;

  RETURN v_margin;
END;
$function$;
COMMENT ON FUNCTION public._speed_cashout_margin(p_asset text, p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision) IS
  $$0051 Phase 2C: reads coefficients from speed_market_config per (asset, duration); fee_config fallback. Direction-matching invariant enforced by formula shape in speed_execute_cashout. New signature replaces (duration, ...) — old sig dropped.$$;
GRANT EXECUTE ON FUNCTION public._speed_cashout_margin(p_asset text, p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_cashout_margin(p_asset text, p_duration speed_duration, p_is_winning boolean, p_mark_prob numeric, p_seconds_left double precision) TO sooqadmin;