-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0028_pricing_engine_v2.sql:200
-- Last extracted: 2026-05-07T11:37:17.334Z
CREATE OR REPLACE FUNCTION public._speed_update_daily_ngr(p_stake_in numeric DEFAULT 0, p_payout_out numeric DEFAULT 0, p_cashout_out numeric DEFAULT 0, p_refund_out numeric DEFAULT 0)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_floor          DECIMAL;
  v_new_ngr        DECIMAL;
  v_existing_trip  TIMESTAMPTZ;
  v_today          DATE := _speed_utc_today();
BEGIN
  INSERT INTO speed_daily_ngr (
    ngr_date, stake_in, payout_out, cashout_out, refund_out, updated_at
  ) VALUES (
    v_today,
    COALESCE(p_stake_in, 0),
    COALESCE(p_payout_out, 0),
    COALESCE(p_cashout_out, 0),
    COALESCE(p_refund_out, 0),
    NOW()
  )
  ON CONFLICT (ngr_date) DO UPDATE
    SET stake_in    = speed_daily_ngr.stake_in    + EXCLUDED.stake_in,
        payout_out  = speed_daily_ngr.payout_out  + EXCLUDED.payout_out,
        cashout_out = speed_daily_ngr.cashout_out + EXCLUDED.cashout_out,
        refund_out  = speed_daily_ngr.refund_out  + EXCLUDED.refund_out,
        updated_at  = NOW();

  SELECT rate INTO v_floor FROM fee_config WHERE fee_type = 'speed_daily_ngr_floor';
  v_floor := COALESCE(v_floor, -500);

  SELECT ngr, circuit_tripped_at INTO v_new_ngr, v_existing_trip
  FROM speed_daily_ngr WHERE ngr_date = v_today;

  IF v_existing_trip IS NULL AND v_new_ngr < v_floor THEN
    UPDATE speed_daily_ngr
       SET circuit_tripped_at = NOW()
     WHERE ngr_date = v_today;
  END IF;
END;
$function$;
COMMENT ON FUNCTION public._speed_update_daily_ngr(p_stake_in numeric, p_payout_out numeric, p_cashout_out numeric, p_refund_out numeric) IS
  $$0028: same body as 0016 except ngr_date key uses _speed_utc_today() instead of CURRENT_DATE. UTC-invariant.$$;
GRANT EXECUTE ON FUNCTION public._speed_update_daily_ngr(p_stake_in numeric, p_payout_out numeric, p_cashout_out numeric, p_refund_out numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_update_daily_ngr(p_stake_in numeric, p_payout_out numeric, p_cashout_out numeric, p_refund_out numeric) TO sooqadmin;