-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0030_quote_execute_parity.sql:97
-- Last extracted: 2026-05-11T18:30:35.470Z
CREATE OR REPLACE FUNCTION public._speed_assert_parity(p_field text, p_expected numeric, p_actual numeric, p_tolerance numeric)
 RETURNS void
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  v_drift  NUMERIC;
BEGIN
  IF p_expected IS NULL THEN
    RETURN;
  END IF;
  IF p_actual = 0 OR p_actual IS NULL THEN
    RAISE EXCEPTION 'PARITY_DRIFT [%]: actual is zero/null, expected=%', p_field, p_expected;
  END IF;
  v_drift := ABS(p_actual - p_expected) / NULLIF(ABS(p_actual), 0);
  IF v_drift > p_tolerance THEN
    RAISE EXCEPTION 'PARITY_DRIFT [%]: expected=% actual=% drift=% > tol=%',
      p_field, p_expected, p_actual, ROUND(v_drift, 6), p_tolerance
      USING HINT = 'Quote stale — refresh and retry';
  END IF;
END;
$function$;
COMMENT ON FUNCTION public._speed_assert_parity(p_field text, p_expected numeric, p_actual numeric, p_tolerance numeric) IS
  $$0030: relative drift assertion helper. Returns silently if expected is NULL (no client snapshot) or drift within tolerance. Raises PARITY_DRIFT otherwise.$$;
GRANT EXECUTE ON FUNCTION public._speed_assert_parity(p_field text, p_expected numeric, p_actual numeric, p_tolerance numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_assert_parity(p_field text, p_expected numeric, p_actual numeric, p_tolerance numeric) TO sooqadmin;