-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0034_pricing_engine_v3.sql:461
-- Last extracted: 2026-05-07T10:39:40.921Z
CREATE OR REPLACE FUNCTION public._speed_max_stake_for_offered(p_duration speed_duration, p_offered_prob double precision)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_trade_max     DECIMAL;
  v_payout_cap    DECIMAL;
  v_liability_cap DECIMAL;
  v_pool          DECIMAL;
  v_max_side_pct  DECIMAL;
  v_by_payout     DECIMAL;
  v_by_liability  DECIMAL;
  v_result        DECIMAL;
BEGIN
  v_trade_max := _speed_get_stake_max(p_duration);

  IF p_duration::TEXT = '5m' THEN
    SELECT rate INTO v_payout_cap FROM fee_config WHERE fee_type = 'speed_entry_max_payout_usd_5m' LIMIT 1;
    v_payout_cap := COALESCE(v_payout_cap, 2500);
  ELSE
    SELECT rate INTO v_payout_cap FROM fee_config WHERE fee_type = 'speed_entry_max_payout_usd_1h' LIMIT 1;
    v_payout_cap := COALESCE(v_payout_cap, 5000);
  END IF;

  SELECT rate INTO v_pool FROM fee_config WHERE fee_type = 'speed_pool_collateral_usd' LIMIT 1;
  SELECT rate INTO v_max_side_pct FROM fee_config WHERE fee_type = 'speed_max_market_exposure_pct' LIMIT 1;
  v_pool := COALESCE(v_pool, 10000);
  v_max_side_pct := COALESCE(v_max_side_pct, 0.25);
  v_liability_cap := v_pool * v_max_side_pct;

  -- max_stake_by_payout: stake / p <= payout_cap → stake <= payout_cap × p
  v_by_payout := v_payout_cap * p_offered_prob;

  -- max_stake_by_liability: liability_per_ticket = stake × (1-p)/p; constrain to <= liability_cap
  -- → stake <= liability_cap × p / (1-p)
  IF p_offered_prob >= 1.0 THEN
    v_by_liability := v_trade_max; -- p=1 means no real risk to platform
  ELSE
    v_by_liability := v_liability_cap * p_offered_prob / (1.0 - p_offered_prob);
  END IF;

  v_result := LEAST(v_trade_max, v_by_payout, v_by_liability);
  IF v_result < 1 THEN v_result := 1; END IF;
  RETURN v_result;
END;
$function$;
COMMENT ON FUNCTION public._speed_max_stake_for_offered(p_duration speed_duration, p_offered_prob double precision) IS
  $$0034: dynamic stake limit formula. Returns max allowed stake given duration + offered_prob, considering trade max, per-ticket payout cap, and per-side liability cap.$$;
GRANT EXECUTE ON FUNCTION public._speed_max_stake_for_offered(p_duration speed_duration, p_offered_prob double precision) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_max_stake_for_offered(p_duration speed_duration, p_offered_prob double precision) TO sooqadmin;