-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0028_pricing_engine_v2.sql:181
-- Last extracted: 2026-05-09T16:57:13.927Z
CREATE OR REPLACE FUNCTION public._speed_utc_midnight()
 RETURNS timestamp with time zone
 LANGUAGE sql
 STABLE
AS $function$ SELECT ((NOW() AT TIME ZONE 'UTC')::date)::TIMESTAMP AT TIME ZONE 'UTC' $function$;
COMMENT ON FUNCTION public._speed_utc_midnight() IS
  $$0028: UTC-invariant midnight TIMESTAMPTZ. Replaces ((NOW() AT TIME ZONE UTC)::date)::TIMESTAMPTZ which was casting a UTC date back to the session timezone.$$;
GRANT EXECUTE ON FUNCTION public._speed_utc_midnight() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_utc_midnight() TO sooqadmin;