-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0028_pricing_engine_v2.sql:176
-- Last extracted: 2026-05-07T10:39:44.872Z
CREATE OR REPLACE FUNCTION public._speed_utc_today()
 RETURNS date
 LANGUAGE sql
 STABLE
AS $function$ SELECT (NOW() AT TIME ZONE 'UTC')::date $function$;
COMMENT ON FUNCTION public._speed_utc_today() IS
  $$0028: UTC-invariant "today" date. Replaces CURRENT_DATE / session-tz casts everywhere a daily window is computed.$$;
GRANT EXECUTE ON FUNCTION public._speed_utc_today() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_utc_today() TO sooqadmin;