-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0034_pricing_engine_v3.sql:461
-- Last extracted: 2026-05-12T13:54:59.881Z
CREATE OR REPLACE FUNCTION public._speed_max_stake_for_offered(p_asset text, p_duration speed_duration, p_offered_prob double precision)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_mc            speed_market_config%ROWTYPE;
  v_trade_max     DECIMAL;
  v_payout_cap    DECIMAL;
  v_liability_cap DECIMAL;
  v_pool          DECIMAL;
  v_max_side_pct  DECIMAL;
  v_by_payout     DECIMAL;
  v_by_liability  DECIMAL;
  v_result        DECIMAL;
BEGIN
  -- 0051 Phase 2C: load per-(asset, duration) row once.
  SELECT * INTO v_mc FROM speed_market_config
  WHERE asset = p_asset AND duration = p_duration;

  -- stake_max from market_config first. Fallback to fee_config per-duration
  -- only for BTC (avoid leaking BTC's stake_max into other assets — gold etc.
  -- need their own market_config rows or a per-asset fee_config key). Final
  -- safety: hardcoded $25.
  IF v_mc.stake_max_usd IS NOT NULL THEN
    v_trade_max := v_mc.stake_max_usd;
  ELSIF p_asset = 'BTC' THEN
    v_trade_max := _speed_get_stake_max(p_duration);
  ELSE
    v_trade_max := 25;
  END IF;

  -- payout cap per (asset, duration) from market_config; fee_config cascade as fallback
  IF v_mc.payout_max_usd IS NOT NULL THEN
    v_payout_cap := v_mc.payout_max_usd;
  ELSIF p_asset = 'GOLD' AND p_duration::TEXT = '5m' THEN
    SELECT rate INTO v_payout_cap FROM fee_config WHERE fee_type = 'speed_entry_max_payout_usd_gold_5m' LIMIT 1;
    v_payout_cap := COALESCE(v_payout_cap, 250);
  ELSIF p_duration::TEXT = '1m' THEN
    SELECT rate INTO v_payout_cap FROM fee_config WHERE fee_type = 'speed_entry_max_payout_usd_1m' LIMIT 1;
    v_payout_cap := COALESCE(v_payout_cap, 250);
  ELSIF p_duration::TEXT = '5m' THEN
    SELECT rate INTO v_payout_cap FROM fee_config WHERE fee_type = 'speed_entry_max_payout_usd_5m' LIMIT 1;
    v_payout_cap := COALESCE(v_payout_cap, 2500);
  ELSE
    SELECT rate INTO v_payout_cap FROM fee_config WHERE fee_type = 'speed_entry_max_payout_usd_1h' LIMIT 1;
    v_payout_cap := COALESCE(v_payout_cap, 5000);
  END IF;

  -- Pool collateral is global (single pool funds all markets); per-side pct is per-market
  SELECT rate INTO v_pool FROM fee_config WHERE fee_type = 'speed_pool_collateral_usd' LIMIT 1;
  SELECT rate INTO v_max_side_pct FROM fee_config WHERE fee_type = 'speed_max_market_exposure_pct' LIMIT 1;
  v_pool := COALESCE(v_pool, 10000);
  v_max_side_pct := COALESCE(v_mc.per_side_pool_pct, v_max_side_pct, 0.25);
  v_liability_cap := v_pool * v_max_side_pct;

  -- max_stake_by_payout: stake / p <= payout_cap → stake <= payout_cap × p
  v_by_payout := v_payout_cap * p_offered_prob;

  -- S0.1 fix retained: liability cap clamp at offered_prob >= 0.98
  IF p_offered_prob >= 0.98 THEN
    v_by_liability := v_trade_max;
  ELSE
    v_by_liability := v_liability_cap * p_offered_prob / (1.0 - p_offered_prob);
  END IF;

  v_result := LEAST(v_trade_max, v_by_payout, v_by_liability);
  IF v_result < 1 THEN v_result := 1; END IF;
  RETURN v_result;
END;
$function$;
COMMENT ON FUNCTION public._speed_max_stake_for_offered(p_asset text, p_duration speed_duration, p_offered_prob double precision) IS
  $$0051 Phase 2C: reads stake_max + payout_cap + per_side_pool_pct from speed_market_config per (asset, duration). Liability clamp at offered>=0.98 retained from S0.1.$$;
GRANT EXECUTE ON FUNCTION public._speed_max_stake_for_offered(p_asset text, p_duration speed_duration, p_offered_prob double precision) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_max_stake_for_offered(p_asset text, p_duration speed_duration, p_offered_prob double precision) TO sooqadmin;