-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0044_sprint_2_clv_throttle/functions/_speed_apply_user_shading.sql
-- Last extracted: 2026-05-08T15:12:14.061Z
CREATE OR REPLACE FUNCTION public._speed_apply_user_shading(p_user_id uuid, p_offered_prob double precision, p_soft_block_threshold double precision DEFAULT 0.95)
 RETURNS double precision
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_enabled        DECIMAL;
  v_min_settled    INT;
  v_min_ci_low     DECIMAL;
  v_max_pp         DECIMAL;
  v_factor         DECIMAL;
  v_max_age_h      DECIMAL;
  v_score          RECORD;
  v_shade_pp       DOUBLE PRECISION;
  v_age_h          DOUBLE PRECISION;
  v_shaded         DOUBLE PRECISION;
  v_max_shaded     DOUBLE PRECISION;
BEGIN
  -- Defensive: NULL/invalid inputs return original
  IF p_user_id IS NULL OR p_offered_prob IS NULL OR p_offered_prob <= 0 OR p_offered_prob >= 1 THEN
    RETURN p_offered_prob;
  END IF;

  -- Master flag
  SELECT rate INTO v_enabled FROM fee_config WHERE fee_type = 'speed_clv_throttle_enabled' LIMIT 1;
  IF COALESCE(v_enabled, 0) = 0 THEN
    RETURN p_offered_prob;
  END IF;

  -- Load user edge score
  SELECT * INTO v_score FROM speed_user_edge_scores WHERE user_id = p_user_id;
  IF NOT FOUND THEN
    RETURN p_offered_prob;
  END IF;

  -- Manual override branch
  IF v_score.manual_override_until IS NOT NULL AND v_score.manual_override_until > NOW() THEN
    IF v_score.manual_shading_factor IS NULL THEN
      RETURN p_offered_prob;  -- admin-exempt
    END IF;
    v_shade_pp := LEAST(v_score.manual_shading_factor::DOUBLE PRECISION, 0.20);
    v_max_shaded := p_soft_block_threshold - 0.001;
    v_shaded := LEAST(v_max_shaded, p_offered_prob + v_shade_pp);
    RETURN GREATEST(p_offered_prob, v_shaded);  -- never lower; defensive
  END IF;

  -- Computed branch — read all gates
  SELECT rate::int INTO v_min_settled FROM fee_config WHERE fee_type = 'speed_clv_min_settled_trades' LIMIT 1;
  SELECT rate INTO v_min_ci_low      FROM fee_config WHERE fee_type = 'speed_clv_min_ci_low' LIMIT 1;
  SELECT rate INTO v_max_pp          FROM fee_config WHERE fee_type = 'speed_clv_max_shading_pp' LIMIT 1;
  SELECT rate INTO v_factor          FROM fee_config WHERE fee_type = 'speed_clv_shading_factor' LIMIT 1;
  SELECT rate INTO v_max_age_h       FROM fee_config WHERE fee_type = 'speed_clv_health_max_age_h' LIMIT 1;

  v_min_settled := COALESCE(v_min_settled, 30);
  v_min_ci_low  := COALESCE(v_min_ci_low, 0.02);
  v_max_pp      := COALESCE(v_max_pp, 0.08);
  v_factor      := COALESCE(v_factor, 0.7);
  v_max_age_h   := COALESCE(v_max_age_h, 36);

  -- Fail-open if cron stale: don't punish users for ops failure
  v_age_h := EXTRACT(EPOCH FROM (NOW() - v_score.last_recomputed_at)) / 3600.0;
  IF v_age_h > v_max_age_h THEN
    RETURN p_offered_prob;
  END IF;

  -- Sample size gate
  IF v_score.settled_trades < v_min_settled THEN
    RETURN p_offered_prob;
  END IF;

  -- Statistical significance gate (one-tailed 95%)
  IF v_score.ci_low <= v_min_ci_low THEN
    RETURN p_offered_prob;
  END IF;

  -- Compute shade. Defensive: edge_score must be positive (already gated by ci_low > 0.02).
  v_shade_pp := LEAST(v_max_pp::DOUBLE PRECISION, v_score.edge_score::DOUBLE PRECISION * v_factor::DOUBLE PRECISION);
  IF v_shade_pp <= 0 THEN
    RETURN p_offered_prob;
  END IF;

  -- Cap below soft_block to avoid pushing user into SOFT_BLOCK from shading
  v_max_shaded := p_soft_block_threshold - 0.001;
  v_shaded := LEAST(v_max_shaded, p_offered_prob + v_shade_pp);
  RETURN GREATEST(p_offered_prob, v_shaded);
END;
$function$;
COMMENT ON FUNCTION public._speed_apply_user_shading(p_user_id uuid, p_offered_prob double precision, p_soft_block_threshold double precision) IS
  $$0044 Sprint 2: per-user CLV shading. Pushes offered_prob UP for users with reliably positive edge. Capped at speed_clv_max_shading_pp. Fail-open if cron stale. Property-tested: shaded_offered >= original_offered always.$$;
GRANT EXECUTE ON FUNCTION public._speed_apply_user_shading(p_user_id uuid, p_offered_prob double precision, p_soft_block_threshold double precision) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public._speed_apply_user_shading(p_user_id uuid, p_offered_prob double precision, p_soft_block_threshold double precision) TO sooqadmin;