-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0013_drop_handle_fee_and_polish.sql:56
-- Last extracted: 2026-05-12T10:35:31.542Z
CREATE OR REPLACE FUNCTION public.speed_fair_prob_over(p_spot numeric, p_strike numeric, p_seconds_left double precision, p_iv numeric)
 RETURNS numeric
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  v_seconds_left DOUBLE PRECISION;
  v_years_left   DOUBLE PRECISION;
  v_sigma_sqrt_t DOUBLE PRECISION;
  v_d2           DOUBLE PRECISION;
  v_iv_dbl       DOUBLE PRECISION;
  v_fair         DOUBLE PRECISION;
BEGIN
  -- Guard: any non-positive price kills LN(). Bail to 0.5 (no info)
  -- so the trade RPC at least gets a callable prob and surfaces the
  -- problem upstream via the freshness gate / oracle-unavailable check.
  IF p_spot IS NULL OR p_strike IS NULL OR p_spot <= 0 OR p_strike <= 0 THEN
    RETURN 0.5::DECIMAL;
  END IF;

  v_seconds_left := GREATEST(p_seconds_left, 1.0);
  v_years_left := v_seconds_left / (365.0 * 24.0 * 3600.0);
  v_iv_dbl := p_iv::DOUBLE PRECISION;
  v_sigma_sqrt_t := v_iv_dbl * SQRT(v_years_left);

  IF v_sigma_sqrt_t = 0 THEN
    RETURN CASE WHEN p_spot > p_strike THEN 0.99 ELSE 0.01 END;
  END IF;

  v_d2 := (LN(p_spot::DOUBLE PRECISION / p_strike::DOUBLE PRECISION)
           - (v_iv_dbl * v_iv_dbl * v_years_left) / 2.0) / v_sigma_sqrt_t;
  v_fair := normal_cdf(v_d2);

  RETURN GREATEST(0.01, LEAST(0.99, v_fair))::DECIMAL;
END;
$function$;
GRANT EXECUTE ON FUNCTION public.speed_fair_prob_over(p_spot numeric, p_strike numeric, p_seconds_left double precision, p_iv numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.speed_fair_prob_over(p_spot numeric, p_strike numeric, p_seconds_left double precision, p_iv numeric) TO sooqadmin;