-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0021_resolve_type_cast_fix.sql:25
-- Last extracted: 2026-05-07T11:37:15.341Z
CREATE OR REPLACE FUNCTION public.speed_resolve_market(p_market_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_lock_acquired   BOOLEAN;
  v_market          RECORD;
  v_outcome         speed_market_outcome;

  v_exact_tick      RECORD;
  v_tick_5s_before  RECORD;
  v_price_delta_pct DECIMAL;
  v_wick_threshold  DECIMAL;
  v_wick_detected   BOOLEAN := FALSE;
  v_median_price    DECIMAL;
  v_median_count    INTEGER;
  v_settlement_price DECIMAL;
  v_raw_ticks       JSONB;

  v_pos             RECORD;
  v_payout          DECIMAL;
  v_winners         INTEGER := 0;
  v_losers          INTEGER := 0;
  v_refunded        INTEGER := 0;
  v_total_paid      DECIMAL := 0;
  v_total_refunded  DECIMAL := 0;
  v_total_stake     DECIMAL := 0;
  v_existing        RECORD;
  v_new_balance     DECIMAL;
  v_voided          BOOLEAN := FALSE;
  v_void_reason     TEXT;
BEGIN
  PERFORM set_config('app.trigger_bypass', 'true', true);

  v_lock_acquired := pg_try_advisory_xact_lock(hashtext('speed_resolve_' || p_market_id::TEXT));
  IF NOT v_lock_acquired THEN
    RETURN jsonb_build_object('skipped', TRUE, 'reason', 'Another invocation is already resolving this market');
  END IF;

  SELECT * INTO v_market FROM speed_markets WHERE id = p_market_id FOR UPDATE;
  IF v_market IS NULL THEN
    RAISE EXCEPTION 'Market not found';
  END IF;
  IF v_market.status NOT IN ('open','resolving') THEN
    RETURN jsonb_build_object('skipped', TRUE, 'status', v_market.status, 'reason', 'Market not in resolvable state');
  END IF;
  IF NOW() < v_market.closes_at THEN
    RAISE EXCEPTION 'Market has not closed yet';
  END IF;

  UPDATE speed_markets SET status = 'resolving', updated_at = NOW()
  WHERE id = p_market_id AND status = 'open';

  SELECT price, ts AS received_at
  INTO v_exact_tick
  FROM speed_oracle_ticks
  WHERE asset = v_market.asset AND ts <= v_market.closes_at
  ORDER BY ts DESC
  LIMIT 1;

  IF v_exact_tick IS NULL THEN
    v_voided := TRUE;
    v_void_reason := 'No oracle tick at or before close';
  END IF;

  IF NOT v_voided THEN
    SELECT price, ts AS received_at
    INTO v_tick_5s_before
    FROM speed_oracle_ticks
    WHERE asset = v_market.asset
      AND ts <= v_market.closes_at - INTERVAL '5 seconds'
    ORDER BY ts DESC
    LIMIT 1;

    IF v_tick_5s_before IS NOT NULL AND v_tick_5s_before.price > 0 THEN
      v_price_delta_pct := ABS(v_exact_tick.price - v_tick_5s_before.price) / v_tick_5s_before.price;

      SELECT rate INTO v_wick_threshold FROM fee_config WHERE fee_type = 'speed_wick_threshold_pct';
      v_wick_threshold := COALESCE(v_wick_threshold, 0.001);

      IF v_wick_threshold > 0 AND v_price_delta_pct > v_wick_threshold THEN
        v_wick_detected := TRUE;
      END IF;
    END IF;
  END IF;

  IF v_wick_detected THEN
    WITH last_ticks AS (
      SELECT price
      FROM speed_oracle_ticks
      WHERE asset = v_market.asset AND ts <= v_market.closes_at
      ORDER BY ts DESC
      LIMIT 30
    )
    SELECT
      PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY price)::DECIMAL,
      COUNT(*)
    INTO v_median_price, v_median_count
    FROM last_ticks;

    IF v_median_price IS NULL OR v_median_count < 5 THEN
      v_voided := TRUE;
      v_void_reason := 'Wick detected but insufficient ticks for median fallback';
    END IF;
  END IF;

  IF NOT v_voided THEN
    SELECT jsonb_agg(jsonb_build_object('ts', ts, 'price', price) ORDER BY ts ASC)
    INTO v_raw_ticks
    FROM (
      SELECT ts, price FROM speed_oracle_ticks
      WHERE asset = v_market.asset AND ts <= v_market.closes_at
      ORDER BY ts DESC
      LIMIT 30
    ) sub;
  END IF;

  IF v_voided THEN
    FOR v_pos IN
      SELECT * FROM speed_positions WHERE market_id = p_market_id AND status = 'open'
    LOOP
      SELECT * INTO v_existing FROM speed_settlements WHERE position_id = v_pos.id;
      IF FOUND THEN CONTINUE; END IF;

      v_total_stake := v_total_stake + v_pos.stake;

      UPDATE users SET balance_usd = balance_usd + v_pos.stake, updated_at = NOW()
      WHERE id = v_pos.user_id
      RETURNING balance_usd INTO v_new_balance;

      INSERT INTO transactions (user_id, type, amount, balance_after, reference_id, description)
      VALUES (v_pos.user_id, 'speed_refund', v_pos.stake, v_new_balance, v_pos.id,
              'Speed market voided — full refund');

      UPDATE speed_positions SET status = 'refunded', payout_amount = v_pos.stake, closed_at = NOW()
      WHERE id = v_pos.id;

      INSERT INTO speed_settlements (position_id, market_id, user_id, outcome, payout_amount)
      VALUES (v_pos.id, p_market_id, v_pos.user_id, 'at_strike', v_pos.stake);

      v_refunded := v_refunded + 1;
      v_total_refunded := v_total_refunded + v_pos.stake;
    END LOOP;

    UPDATE speed_markets SET status = 'voided', updated_at = NOW(), resolved_at = NOW(),
                            twap_at_close = NULL, void_reason = v_void_reason
    WHERE id = p_market_id;

    PERFORM _speed_update_daily_ngr(v_total_stake, 0, 0, v_total_refunded);

    RETURN jsonb_build_object(
      'success', TRUE, 'voided', TRUE, 'reason', v_void_reason,
      'refunded', v_refunded,
      'refunded_total', ROUND(v_total_refunded, 2)
    );
  END IF;

  v_settlement_price := COALESCE(v_median_price, v_exact_tick.price);

  INSERT INTO speed_market_settlement_audit (
    market_id, resolved_at, closes_at,
    exact_tick_price, exact_tick_at,
    price_5s_before, price_delta_pct,
    wick_detected, fallback_median_price, fallback_tick_count,
    final_settlement_price, raw_ticks
  ) VALUES (
    p_market_id, NOW(), v_market.closes_at,
    v_exact_tick.price, v_exact_tick.received_at,
    CASE WHEN v_tick_5s_before IS NOT NULL THEN v_tick_5s_before.price ELSE NULL END,
    v_price_delta_pct,
    v_wick_detected, v_median_price, v_median_count,
    v_settlement_price, v_raw_ticks
  ) ON CONFLICT (market_id) DO UPDATE
    SET resolved_at = EXCLUDED.resolved_at,
        exact_tick_price = EXCLUDED.exact_tick_price,
        exact_tick_at = EXCLUDED.exact_tick_at,
        price_5s_before = EXCLUDED.price_5s_before,
        price_delta_pct = EXCLUDED.price_delta_pct,
        wick_detected = EXCLUDED.wick_detected,
        fallback_median_price = EXCLUDED.fallback_median_price,
        fallback_tick_count = EXCLUDED.fallback_tick_count,
        final_settlement_price = EXCLUDED.final_settlement_price,
        raw_ticks = EXCLUDED.raw_ticks;

  IF v_settlement_price > v_market.strike_price THEN
    v_outcome := 'over';
  ELSIF v_settlement_price < v_market.strike_price THEN
    v_outcome := 'under';
  ELSE
    v_outcome := 'at_strike';
  END IF;

  FOR v_pos IN
    SELECT * FROM speed_positions WHERE market_id = p_market_id AND status = 'open'
  LOOP
    SELECT * INTO v_existing FROM speed_settlements WHERE position_id = v_pos.id;
    IF FOUND THEN CONTINUE; END IF;

    v_total_stake := v_total_stake + v_pos.stake;

    IF v_outcome = 'at_strike' THEN
      v_payout := v_pos.stake;
      UPDATE users SET balance_usd = balance_usd + v_payout, updated_at = NOW()
      WHERE id = v_pos.user_id
      RETURNING balance_usd INTO v_new_balance;

      INSERT INTO transactions (user_id, type, amount, balance_after, reference_id, description)
      VALUES (v_pos.user_id, 'speed_refund', v_payout, v_new_balance, v_pos.id,
              'Speed market settled at strike — push refund');

      UPDATE speed_positions SET status = 'refunded', payout_amount = v_payout, closed_at = NOW()
      WHERE id = v_pos.id;
      v_refunded := v_refunded + 1;
      v_total_refunded := v_total_refunded + v_payout;

    -- 0021: cast both sides to TEXT — speed_side enum has no implicit
    -- equality with text and the prior `v_pos.side = v_outcome::TEXT`
    -- raised "operator does not exist: speed_side = text" at runtime.
    ELSIF v_pos.side::TEXT = v_outcome::TEXT THEN
      v_payout := ROUND(v_pos.stake / v_pos.entry_offered_prob, 2);
      v_winners := v_winners + 1;
      v_total_paid := v_total_paid + v_payout;

      UPDATE users SET balance_usd = balance_usd + v_payout, updated_at = NOW()
      WHERE id = v_pos.user_id
      RETURNING balance_usd INTO v_new_balance;

      INSERT INTO transactions (user_id, type, amount, balance_after, reference_id, description)
      VALUES (v_pos.user_id, 'speed_payout', v_payout, v_new_balance, v_pos.id,
              'Speed payout (' || v_pos.side || ')');

      UPDATE speed_positions SET status = 'won', payout_amount = v_payout, closed_at = NOW()
      WHERE id = v_pos.id;
    ELSE
      v_losers := v_losers + 1;
      v_payout := 0;
      UPDATE speed_positions SET status = 'lost', payout_amount = 0, closed_at = NOW()
      WHERE id = v_pos.id;
    END IF;

    INSERT INTO speed_settlements (position_id, market_id, user_id, outcome, payout_amount)
    VALUES (v_pos.id, p_market_id, v_pos.user_id, v_outcome, v_payout);
  END LOOP;

  UPDATE speed_markets SET status = 'resolved', updated_at = NOW(), resolved_at = NOW(),
                          twap_at_close = v_settlement_price, outcome = v_outcome
  WHERE id = p_market_id;

  PERFORM _speed_update_daily_ngr(v_total_stake, v_total_paid, 0, v_total_refunded);

  RETURN jsonb_build_object(
    'success', TRUE, 'voided', FALSE, 'outcome', v_outcome,
    'settlement_price', ROUND(v_settlement_price, 8),
    'wick_detected', v_wick_detected,
    'price_delta_pct', v_price_delta_pct,
    'strike', ROUND(v_market.strike_price, 8),
    'winners', v_winners, 'losers', v_losers, 'refunded', v_refunded,
    'total_paid', ROUND(v_total_paid, 2),
    'total_refunded', ROUND(v_total_refunded, 2)
  );
END;
$function$;
COMMENT ON FUNCTION public.speed_resolve_market(p_market_id uuid) IS
  $$0021: hotfix for type-cast bug in mig 0016. Resolves a speed market with exact-tick + wick detector + audit row + NGR cache update. Same behavior as mig 0016 §6, only the v_pos.side comparison is corrected.$$;
GRANT EXECUTE ON FUNCTION public.speed_resolve_market(p_market_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.speed_resolve_market(p_market_id uuid) TO sooqadmin;