-- Canonical definition extracted from pg_proc on staging RDS.
-- DO NOT EDIT THIS FILE BY HAND. To change the function:
--   1. Author a new migration with CREATE OR REPLACE FUNCTION ...
--   2. Apply it (scripts/apply-mig.mjs --name 0035_my_change)
--   3. Re-run scripts/extract-functions.mjs to refresh this file
--
-- Source of truth (latest known migration touching this function):
--   0004_speed_cron.sql:151
-- Last extracted: 2026-05-07T11:37:15.705Z
CREATE OR REPLACE FUNCTION public.speed_resolve_expired_markets()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_market_id UUID;
  v_result    JSONB;
  v_resolved  INTEGER := 0;
  v_voided    INTEGER := 0;
  v_failed    INTEGER := 0;
  v_errors    JSONB := '[]'::JSONB;
BEGIN
  FOR v_market_id IN
    SELECT id FROM speed_markets
    WHERE status IN ('open', 'resolving') AND closes_at <= NOW()
    ORDER BY closes_at
  LOOP
    BEGIN
      v_result := speed_resolve_market(v_market_id);

      IF COALESCE((v_result->>'voided')::BOOLEAN, FALSE) THEN
        v_voided := v_voided + 1;
      ELSIF COALESCE((v_result->>'success')::BOOLEAN, FALSE) THEN
        v_resolved := v_resolved + 1;
      END IF;
    EXCEPTION WHEN OTHERS THEN
      v_failed := v_failed + 1;
      v_errors := v_errors || jsonb_build_object('market_id', v_market_id, 'error', SQLERRM);
      RAISE NOTICE 'speed_resolve_expired_markets: market % failed: %', v_market_id, SQLERRM;
    END;
  END LOOP;

  RETURN jsonb_build_object(
    'success', TRUE,
    'resolved', v_resolved,
    'voided', v_voided,
    'failed', v_failed,
    'errors', v_errors
  );
END;
$function$;
GRANT EXECUTE ON FUNCTION public.speed_resolve_expired_markets() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.speed_resolve_expired_markets() TO sooqadmin;